variables:
- group: demo-vm-deploy

jobs:
- job:
  displayName: Build the Packer with Ansible Docker Image, and push it to Container Registry
  timeoutInMinutes: 360

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
    - task: Docker@2
      displayName: Login to Azure Container Registry
      inputs:
        command: login
        containerRegistry: dsfAcrConnection
    - task: Docker@2
      displayName: Build web
      inputs:
        command: build
        Dockerfile: $(Build.SourcesDirectory)/Dockerfile
        buildContext: $(Build.SourcesDirectory)
        repository: dsf/build
        tags: |
          latest
          $(Build.BuildId)

    - task: Docker@2
      displayName: Push web
      inputs:
        command: push
        repository: dsf/build
        tags: |
          latest
          $(Build.BuildId)
