variables:
  containerRegistry: 'demovmcontainer'
  azureSubscription: 'PoC'
  repositoryName: 'build-packer-ansible'

jobs:
- job:
  displayName: ${{ format('Build the Packer with Ansible Docker Image, and push it to Container Registry {0}', variables.containerRegistry) }}
  timeoutInMinutes: 360

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
    - task: AzureCLI@1
      displayName: Build and Push '${{variables.containerRegistry}}.azurecr.io/${{variables.repositoryName}}' Docker image
      inputs:
        azureSubscription: ${{variables.azureSubscription}}
        scriptLocation: inlineScript
        inlineScript:  |
          docker build -t ${{variables.containerRegistry}}.azurecr.io/${{variables.repositoryName}} $(Build.SourcesDirectory)/Infrastructure/PackerAnsible/.
          az acr login --name ${{variables.containerRegistry}}
          docker push ${{variables.containerRegistry}}.azurecr.io/${{variables.repositoryName}}:latest
